// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpHwfMdLdF52B3fWvdzj1b8NNBsprli4A',
    appId: '1:918968462884:android:dd65196cee41ec6eb8f2b1',
    messagingSenderId: '918968462884',
    projectId: 'authenticationriverpod-3a400',
    databaseURL: 'https://authenticationriverpod-3a400-default-rtdb.firebaseio.com',
    storageBucket: 'authenticationriverpod-3a400.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCMRkpfLVgSxVMcCOxIjneszjf1tBovAlQ',
    appId: '1:918968462884:ios:172b22d3dcfda3f7b8f2b1',
    messagingSenderId: '918968462884',
    projectId: 'authenticationriverpod-3a400',
    databaseURL: 'https://authenticationriverpod-3a400-default-rtdb.firebaseio.com',
    storageBucket: 'authenticationriverpod-3a400.firebasestorage.app',
    iosClientId: '918968462884-smcuks1igtgcc23g0o1ktfejd4o40ls3.apps.googleusercontent.com',
    iosBundleId: 'com.todo.app.todoApp',
  );
}
